language: go
env:
  - CONSUL_URL=https://dl.bintray.com/mitchellh/consul/0.4.1_linux_amd64.zip
  - CONSUL_URL=https://dl.bintray.com/mitchellh/consul/0.5.1_linux_amd64.zip
go:
  - 1.2
  - 1.3
  - 1.4
before_install:
  - go get code.google.com/p/go.tools/cmd/vet
  - go get github.com/golang/lint/golint
  - go get github.com/tools/godep
  - wget "$CONSUL_URL"
  - unzip "0.4.1_linux_amd64.zip"
script:
  - ./consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul &
  - sleep 5  # sleep while it starts up
  - godep go test  -tags integration
  - go vet ./...
  - $HOME/gopath/bin/golint **/*.go
  - LINTED=$($HOME/gopath/bin/golint **/*.go| wc -l); if [ $LINTED -gt 0 ]; then echo "golint: $LINTED statements not up to spec, please run golint and follow the suggestions." && exit 1; fi
after_script:
  - FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt: $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 1; fi
